config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:show]
    resources :customers, only: [:index, :show, :edit, :update]
  end
  
  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    get "customers/information/edit", to: "customers#edit", as: "edit_customer"
    get "customers/my_page", to: "customers#show", as: "show_customer"
    patch "customers/information", to: "customers#update", as: "customer"
    resources :items, only: [:index, :show]
    resources :customers, except: [:new, :create, :show, :index, :edit, :update, :destroy] do
      collection do
        get "confirm"
        patch "withdraw"
      end
    end
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete "destroy_all"
      end
    end
    post 'orders/confirm', to:
    'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get "thanks"
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items, dependent: :destroy
    belongs_to :customer
    enum payment_method: { credit_card: 0, transfer: 1 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :authenticate_admin!
    
    def show
        @order = Order.find(params[:id])
        @order_items = OrderItem.where(order_id: params[:id])
        @total_item_amount = @order_items.sum{|order_item| order_item.subtotal}
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
    <label class="bg-secondary h4 ml-5 px-2 mb-3">注文履歴詳細</label>
    <div class="row-7">
        <table>
            <tr>
                <th class="col-4">購入者</th>
                <td><%= link_to @order.customer.fullname, admin_customer_path(@order.customer_id), class: "text-dark" %></td>
            </tr>
            
            <tr>
                <th class="col-4">注文日</th>
                <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
            </tr>
            
            <tr>
                <th class="col-4">配送先</th>
                <td>
                    <%= @order.customer.address_display %></br>
                    <%= @order.customer.fullname %>
                </td>
            </tr>
            
            <tr>
                <th class="col-4">支払方法</th>
                <td><%= @order.payment_method_i18n %></td>
            </tr>
        </table>
    </div>
    
    <div class="row mt-3">
        <table class="col table border-bottom">
            <tr class="table-secondary">
                <th>商品名</th>
                <th>単価(税込)</th>
                <th>数量</th>
                <th>小計</th>
            </tr>
            
            <% @order_items.each do |order_item| %>
            <tr>
                <td><%= order_item.item.name %></td>
                <td><%= order_item.uniti_price_including_tax %></td>
                <td><%= order_item.quantity %></td>
                <td><%= order_item.subtotal.to_s(:delimited) %></td>
            </tr>
            <% end %>
        </table>
        
        <div class="col-2 offset-1 h-50 px-0 pt-4 mt-5">
            <table class="mt-5">
                <tr>
                    <th>商品合計</th>
                    <td><%= @total_item_amount.to_s(:delimited) %>円</td>
                </tr>
                <tr>
                    <th>送料</th>
                    <td><%= @order.shipping_fee %>円</td>
                </tr>
                <tr>
                    <th>請求金額合計</th>
                    <td class="font-weight-bold"><%= @order.billing_amount.to_s(:delimited) %>円</td>
                </tr>
            </table>
        </div>
        
    </div>
</div>