config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:show]
    resources :customers, only: [:index, :show, :edit, :update]
  end
  
  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    get "customers/information/edit", to: "customers#edit", as: "edit_customer"
    get "customers/my_page", to: "customers#show", as: "show_customer"
    patch "customers/information", to: "customers#update", as: "customer"
    resources :items, only: [:index, :show]
    resources :customers, except: [:new, :create, :show, :index, :edit, :update, :destroy] do
      collection do
        get "confirm"
        patch "withdraw"
      end
    end
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete "destroy_all"
      end
    end
    post 'orders/confirm', to:
    'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get "thanks"
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    def subtotal
        item.add_tax_included_price * amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def status_label
    status_class = is_active? ? 'text-success' : 'text-secondary'
    "<span class='#{status_class}'>#{is_active? ? '有効' : '退会'}</span>".html_safe
  end
  
  def fullname
    last_name + "　" + first_name
  end
  
  def fullname_kana
    last_name_kana + "　" + first_name_kana
  end
  
  def address_display
    "〒" + postal_code + " " + address
  end
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :item_image
    
    has_many :cart_items, dependent: :destroy
    has_many :order_items, dependent: :destroy
    
    def get_item_image(width, height)
        unless item_image.attached?
            file_path = Rails.root.join("app/assets/images/no_image.jpg")
            item_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
        end
        item_image.variant(resize_to_limit: [width, height]).processed
    end
    
    def add_tax_included_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items, dependent: :destroy
    belongs_to :customer
    enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :item
    belongs_to :order
    
    def subtotal
        quantity * item.add_tax_included_price
    end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    before_action :authenticate_admin!
    
    def index
        @customers = Customer.page(params[:page])
    end
    
    def show
        @customer = Customer.find(params[:id])
    end
    
    def edit
        @customer = Customer.find(params[:id])
    end
    
    def update
        @customer = Customer.find(params[:id])
        @customer.update(customer_params)
        redirect_to admin_customer_path(@customer)
    end
    
    private
    
    def customer_params
        params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active, :email)
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!
    
    def top
        @orders = Order.order(created_at: :desc).page(params[:page])
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!
    
    def index
        @items = Item.page(params[:page])
    end
    
    def new
        @item = Item.new
    end
    
    def create
        @item = Item.new(item_params)
        @item.save
        redirect_to admin_item_path(@item.id)
    end
    
    def show
        @item = Item.find(params[:id])
    end
    
    def edit
        @item = Item.find(params[:id])
    end
    
    def update
        @item = Item.find(params[:id])
        @item.update(item_params)
        redirect_to admin_item_path(@item.id)
    end
    
    private
    
    def item_params
        params.require(:item).permit(:name, :introduction, :price, :item_image)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :authenticate_admin!
    
    def show
        @order = Order.find(params[:id])
        @order_items = OrderItem.where(order_id: params[:id])
        @total_item_amount = @order_items.sum{|order_item| order_item.subtotal}
    end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  before_action :authenticate_admin!
  
  def after_sign_in_path_for(resource)
    admin_root_path
  end
  
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/a7b69aa32a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="border border-dark my-2 mx-4">
    <header class="border-bottom border-dark py-3">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <%= link_to "LOGO", root_path, class: "navbar-brand text-dark border border-dark px-5" %>
    
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
    
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li class="nav-item mr-4">
                  <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark nav-link text-dark" %>
                </li>
                <li class="nav-item mr-4">
                  <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-dark nav-link text-dark" %>
                </li>
                <li class="nav-item mr-4">
                  <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-dark nav-link text-dark" %>
                </li>
                <li class="nav-item mr-4">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark nav-link text-dark" %>
                </li>
              <% elsif customer_signed_in? %>
                <li class="nav-item mr-4">
                  <%= link_to "マイページ", show_customer_path, class: "btn btn-outline-dark nav-link text-dark" %>
                </li>
                <li class="nav-item mr-4">
                  <%= link_to "商品一覧", items_path, class: "btn btn-outline-dark nav-link text-dark" %>
                </li>
                <li class="nav-item mr-4">
                  <%= link_to "カート", cart_items_path, class: "btn btn-outline-dark nav-link text-dark px-3" %>
                </li>
                <li class="nav-item mr-4">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark nav-link text-dark" %>
                </li>
              <% else %>
                <li class="nav-item mr-4">
                  <%= link_to "About", about_path, class: "btn btn-outline-dark nav-link text-dark px-3" %>
                </li>
                <li class="nav-item mr-4">
                  <%= link_to "商品一覧", items_path, class: "btn btn-outline-dark nav-link text-dark" %>
                </li>
                <li class="nav-item mr-4">
                  <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark nav-link text-dark" %>
                </li>
                <li class="nav-item mr-4">
                  <%= link_to "ログイン", customer_session_path, class: "btn btn-outline-dark nav-link text-dark" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="my-5">
      <%= yield %>
    </main>
    <footer class="border-top border-dark p-5"></footer>
  </body>
</html>